import os
import yaml
from pathlib import Path

def generate_tools_doc(root_dir: Path) -> str:
    tools_dir = root_dir / "config" / "tools"
    
    doc = [
        "# Available Tools",
        "",
        "This file is auto-generated from the tool manifests in `config/tools/`.",
        "Do not edit this file directly.",
        "",
    ]
    
    for filename in sorted(os.listdir(tools_dir)):
        if not filename.endswith(".yaml"):
            continue
            
        with open(tools_dir / filename, "r", encoding="utf-8") as f:
            manifest = yaml.safe_load(f)
            
        doc.append(f"## {filename.removesuffix('.yaml').title()} Tools")
        doc.append("")
        
        tools = manifest.get("tools", [])
        for tool in tools:
            name = tool.get("name")
            desc = tool.get("description", "No description")
            tier = tool.get("tier", "auto")
            
            doc.append(f"### `{name}`")
            doc.append(f"**Permission tier**: `{tier}`")
            doc.append("")
            doc.append(f"{desc}")
            doc.append("")
            
            args = tool.get("arguments", {})
            if args:
                doc.append("**Arguments:**")
                for arg_name, arg_desc in args.items():
                    doc.append(f"- `{arg_name}`: {arg_desc}")
                doc.append("")
                
    return "\n".join(doc)

def main():
    root_dir = Path(__file__).parent.parent
    doc = generate_tools_doc(root_dir)
    out_path = root_dir / "config" / "tools.md"
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(doc)
    print(f"Wrote {out_path}")

if __name__ == "__main__":
    main()
