"""Agent verification script.

Runs:
1. All agent test suites (T1-T8 + supporting tests)
2. One-entry-path check
3. tools.md freshness check (generated from registry)
4. Security checks

Prints a PASS/FAIL table and exits nonzero on any failure.

Usage:
    cd backend && python -m pytest ../scripts/verify_agent.py --tb=short
    OR:
    python scripts/verify_agent.py
"""

from __future__ import annotations

import importlib
import subprocess
import sys
import time
from pathlib import Path
from typing import List, Tuple

ROOT = Path(__file__).parent.parent
BACKEND = ROOT / "backend"
TESTS = ROOT / "tests"

try:
    from dotenv import load_dotenv
    if (ROOT / ".env").exists():
        load_dotenv(ROOT / ".env")
except ImportError:
    pass


# ---------------------------------------------------------------------------
# Test suites to run (relative to ROOT)
# ---------------------------------------------------------------------------

TEST_SUITES = [
    ("T1-T8 Scenarios", "tests/test_agent_scenarios.py"),
    ("AgentState", "tests/test_agent_state.py"),
    ("Safety + Security", "tests/test_agent_safety.py"),
    ("LLM Parsing", "tests/test_llm_parsing.py"),
    ("Memory Integration", "tests/test_agent_memory.py"),
    ("Token Budget", "tests/test_agent_budget.py"),
    ("Single Entry Path", "tests/test_agent_regression.py"),
    ("Tools Doc Freshness", "tests/test_tools_doc.py"),
    ("Tool Selector", "tests/test_tool_selector.py"),
    ("Agent Loop", "tests/test_agent_loop.py"),
    ("LLM Gateway", "tests/test_llm_gateway.py"),
    ("Agent Permissions", "tests/test_agent_permissions.py"),
    ("Agent Events", "tests/test_agent_events.py"),
]



def run_pytest(test_path: str) -> Tuple[bool, str]:
    """Run a pytest file and return (passed, output)."""
    cmd = [sys.executable, "-m", "pytest", test_path, "-v", "--tb=short", "--no-header"]
    result = subprocess.run(
        cmd,
        cwd=str(ROOT),
        capture_output=True,
        text=True,
        timeout=120,
    )
    passed = result.returncode == 0
    output = result.stdout + result.stderr
    return passed, output


def check_single_entry_path() -> Tuple[bool, str]:
    """Verify exactly one canonical agent entry point."""
    try:
        sys.path.insert(0, str(BACKEND))
        from app.agent.brain import run_agent_entrypoint, JarvisBrain  # noqa: F401
        from app.agent.loop import run_agent  # noqa: F401

        # graph/workflow.py must be RETIRED
        workflow = ROOT / "backend" / "app" / "graph" / "workflow.py"
        if workflow.exists():
            content = workflow.read_text(encoding="utf-8", errors="replace")
            if "RETIRED" not in content:
                return False, "graph/workflow.py is not marked RETIRED"

        return True, "Single entry path OK: run_agent_entrypoint -> JarvisBrain.run -> run_agent"
    except ImportError as e:
        return False, f"Import error: {e}"


def check_tools_md_freshness() -> Tuple[bool, str]:
    """Verify tools.md exists and is a placeholder or generated."""
    tools_md = ROOT / "config" / "tools.md"
    if not tools_md.exists():
        return True, "tools.md not required to pre-exist (generated by scripts/generate_tools_doc.py)"

    content = tools_md.read_text(encoding="utf-8", errors="replace")
    # tools.md should not be hand-written with hardcoded names
    # The freshness test in tests/test_tools_doc.py is the authoritative check
    return True, f"tools.md exists ({len(content)} chars)"


def check_soul_md_exists() -> Tuple[bool, str]:
    """Verify soul.md prompt file exists."""
    soul_path = ROOT / "backend" / "app" / "agent" / "prompts" / "soul.md"
    if not soul_path.exists():
        return False, f"soul.md not found at {soul_path}"
    content = soul_path.read_text(encoding="utf-8", errors="replace")
    if "memory_visibility" not in content:
        return False, "soul.md missing memory_visibility knob"
    return True, f"soul.md OK ({len(content)} chars)"


def check_agents_md_exists() -> Tuple[bool, str]:
    """Verify agents.md prompt file exists with safety rules."""
    agents_path = ROOT / "backend" / "app" / "agent" / "prompts" / "agents.md"
    if not agents_path.exists():
        return False, f"agents.md not found at {agents_path}"
    content = agents_path.read_text(encoding="utf-8", errors="replace")
    if "LOCKED SAFETY RULES" not in content:
        return False, "agents.md missing LOCKED SAFETY RULES section"
    return True, f"agents.md OK ({len(content)} chars)"


def check_no_env_leakage() -> Tuple[bool, str]:
    """Verify .env is gitignored and not tracked."""
    result = subprocess.run(
        ["git", "ls-files", ".env"],
        cwd=str(ROOT),
        capture_output=True,
        text=True,
        timeout=10,
    )
    if result.stdout.strip():
        return False, "CRITICAL: .env is tracked by git! Remove it immediately."
    return True, ".env is not tracked by git (safe)"


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> int:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    if hasattr(sys.stderr, "reconfigure"):
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")

    print("\n" + "=" * 70)
    print("  JARVIS Agent Verification Suite")
    print("  Branch: agent/core")
    print(f"  Time: {time.strftime('%Y-%m-%d %H:%M:%S')}")
    print("=" * 70 + "\n")

    results: List[Tuple[str, bool, str]] = []
    all_passed = True

    # Run test suites
    for name, path in TEST_SUITES:
        print(f"Running: {name} ({path})")
        try:
            passed, output = run_pytest(path)
        except subprocess.TimeoutExpired:
            passed, output = False, "TIMEOUT"
        except FileNotFoundError:
            passed, output = False, f"Test file not found: {path}"

        results.append((name, passed, output[:200] if not passed else ""))
        if not passed:
            all_passed = False
            print(f"  FAIL: {output[-500:]}\n")
        else:
            print(f"  PASS\n")

    # Run standalone checks
    checks = [
        ("Single Entry Path", check_single_entry_path),
        ("tools.md Freshness", check_tools_md_freshness),
        ("soul.md Exists", check_soul_md_exists),
        ("agents.md Exists", check_agents_md_exists),
        (".env Not Tracked", check_no_env_leakage),
    ]

    for name, check_fn in checks:
        print(f"Checking: {name}")
        try:
            passed, detail = check_fn()
        except Exception as e:
            passed, detail = False, str(e)
        results.append((name, passed, detail if not passed else ""))
        if not passed:
            all_passed = False
        print(f"  {'PASS' if passed else 'FAIL'}: {detail}\n")

    # Print summary table
    print("\n" + "=" * 70)
    print(f"{'Check':<40} {'Status':<10} {'Detail'}")
    print("-" * 70)
    for name, passed, detail in results:
        status = "PASS" if passed else "FAIL"
        detail_short = (detail[:30] + "...") if len(detail) > 30 else detail
        print(f"{name:<40} {status:<10} {detail_short}")

    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    if hasattr(sys.stderr, "reconfigure"):
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")

    print("=" * 70)
    if all_passed:
        print("\n[PASS]  ALL CHECKS PASSED")
        print("\nHandoff sentence:")
        print("  Give me an objective and memory context; I'll decide what to do.")
        print("  Give me the tool registry; I'll decide which tool to call.")
        print("  Give me tool results; I'll decide whether to continue, recover, verify, or finish.")
    else:
        print("\n[FAIL]  SOME CHECKS FAILED -- see details above")

    return 0 if all_passed else 1


if __name__ == "__main__":
    sys.exit(main())
